# Generated by Django 5.2.9 on 2025-12-04 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=200)),
                ('producto', models.CharField(max_length=200)),
                ('ot', models.CharField(max_length=100, unique=True)),
                ('req', models.CharField(blank=True, max_length=200, null=True)),
                ('sol', models.CharField(blank=True, max_length=200, null=True)),
                ('producto_hijo', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('enlace_id', models.CharField(max_length=200)),
                ('comercial', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('pospuesto', 'Pospuesto'), ('cancelado', 'Cancelado'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('ing_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
