# Generated by Django 5.2.9 on 2025-12-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='fecha_estimada',
            field=models.BooleanField(default=False),
        ),
    ]
