# Generated by Django 5.2.9 on 2025-12-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTadmin', '0003_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200, unique=True)),
                ('cliente_normalizado', models.CharField(max_length=200, unique=True)),
                ('segmento', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ot',
            name='cliente_normalizado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ot',
            name='familia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
