# Generated by Django 5.2.9 on 2025-12-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTadmin', '0004_segmentocliente_ot_cliente_normalizado_ot_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='dias_cola_hoy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ot',
            name='mtti',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
